// The first group is artwork from The Met's Open Access collection: every piece
// is out of copyright and released under CC0, so it can be used and altered
// without permission or attribution. We credit it anyway, in the picker.
// The second group is CC0 photography. Between them they cover the two looks a
// host tends to want: a designed invitation, or a picture of the occasion.
const TEMPLATES = [
  { id: 'wedding', label: 'Wedding', file: 'wedding.jpg', category: 'celebration', sourceName: 'William Morris, “Pink and Rose”, ca. 1890 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/337071' },
  { id: 'engagement', label: 'Engagement', file: 'engagement.jpg', category: 'celebration', sourceName: 'Réveillon, floral wallpaper, ca. 1780s · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/367795' },
  { id: 'anniversary', label: 'Anniversary', file: 'anniversary.jpg', category: 'celebration', sourceName: 'Kano Sansetsu, “Old Plum”, 1646 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/44858' },
  { id: 'baby-shower', label: 'Baby Shower', file: 'baby-shower.jpg', category: 'gathering', sourceName: 'William Morris, “Jasmine”, 1872 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/383485' },
  { id: 'birthday', label: 'Birthday', file: 'birthday.jpg', category: 'celebration', sourceName: 'Embroidered cover, present-day Uzbekistan, early 19th c. · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/447384' },
  { id: 'celebration', label: 'Celebration', file: 'celebration.jpg', category: 'gathering', sourceName: 'J.-E.-C. Lachaise, wallpaper design, 19th c. · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/384889' },
  { id: 'quinceanera', label: 'Quinceañera', file: 'quinceanera.jpg', category: 'celebration', sourceName: 'H. Minder fils, paisley textile design, mid-19th c. · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/367779' },
  { id: 'graduation', label: 'Graduation', file: 'graduation.jpg', category: 'celebration', sourceName: 'Nicolas Cochin, engraved flower panel, 1645 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/425820' },
  { id: 'corporate', label: 'Corporate', file: 'corporate.jpg', category: 'statement', sourceName: 'William Morris, “Marigold”, 1875 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/384018' },
  { id: 'holiday-new-year', label: 'Holiday / New Year', file: 'holiday-new-year.jpg', category: 'statement', sourceName: 'Hasegawa Sadanobu, “Kinkakuji seen in Falling Snow” · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/55417' },
  { id: 'housewarming', label: 'Housewarming', file: 'housewarming.jpg', category: 'gathering', sourceName: 'William Morris, “Trellis”, 1864 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/384020' },
  { id: 'retirement', label: 'Retirement', file: 'retirement.jpg', category: 'statement', sourceName: 'Utagawa Hiroshige, “Autumn Moon on the Tama River”, ca. 1838 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/56903' },
  { id: 'sunlit-gathering', label: 'Sunlit Gathering', file: 'sunlit-gathering.jpg', category: 'gathering', sourceName: 'William Morris, “Willow Bough”, 1887 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/384022' },
  // Kept its id so events that already chose it keep their artwork; the label
  // and the art it points at are both new.
  { id: 'citrus-disco', label: 'Festive Bloom', file: 'citrus-disco.jpg', category: 'celebration', sourceName: 'İznik tile panel, Turkey, early 17th c. · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/454352' },

  // A second sweep through the same collection, so a host picking a look has
  // real choice rather than one option per occasion.
  { id: 'roses-and-ribbons', label: 'Roses & Ribbons', file: 'roses-and-ribbons.jpg', category: 'celebration', sourceName: '“Valentine”, ca. 1880 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/732577' },
  { id: 'blush-valentine', label: 'Blush Valentine', file: 'blush-valentine.jpg', category: 'celebration', sourceName: '“Valentine”, 1850–79 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/733079' },
  { id: 'illuminated-page', label: 'Illuminated Page', file: 'illuminated-page.jpg', category: 'statement', sourceName: 'Cano de Aranda, “Spanish Translation of Saint…”, 1446–82 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/469827' },
  { id: 'persian-border', label: 'Persian Border', file: 'persian-border.jpg', category: 'statement', sourceName: 'Fathallah Sani\'zada, “Abraham\'s Sacrifice”, 16th century · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/452106' },
  { id: 'gilded-rosette', label: 'Gilded Rosette', file: 'gilded-rosette.jpg', category: 'statement', sourceName: 'India, “Rosette Bearing the Names and Titles of…”, ca. 1645 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/451286' },
  { id: 'gilded-meadow', label: 'Gilded Meadow', file: 'gilded-meadow.jpg', category: 'statement', sourceName: 'Manohar, “Black Buck”, ca. 1615 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/454624' },
  { id: 'lapis-and-gold', label: 'Lapis & Gold', file: 'lapis-and-gold.jpg', category: 'statement', sourceName: 'Amir Shahi of Sabzavar, “Anthology of Persian Poetry”, 16th century · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/443197' },
  { id: 'persian-manuscript', label: 'Persian Manuscript', file: 'persian-manuscript.jpg', category: 'statement', sourceName: 'Turkey, “Qur\'an Manuscript”, 1851 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/453024' },
  { id: 'chintz-quilt', label: 'Chintz Quilt', file: 'chintz-quilt.jpg', category: 'gathering', sourceName: 'Mary Malvina Cook Taft, “Chintz appliquéd quilt”, ca. 1835–40 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/13869' },
  { id: 'wild-tulip', label: 'Wild Tulip', file: 'wild-tulip.jpg', category: 'gathering', sourceName: 'William Morris, “Wild Tulip”, 1884 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/375808' },
  { id: 'morris-daisy', label: 'Daisy', file: 'morris-daisy.jpg', category: 'gathering', sourceName: 'William Morris, “Daisy”, 1864 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/384017' },
  { id: 'pomegranate', label: 'Pomegranate', file: 'pomegranate.jpg', category: 'gathering', sourceName: 'William Morris, “Fruit”, ca. 1866 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/365338' },
  { id: 'rose-brocade', label: 'Rose Brocade', file: 'rose-brocade.jpg', category: 'celebration', sourceName: 'James Leman, “Panel of brocaded silk”, ca. 1720 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/229658' },
  { id: 'ottoman-vine', label: 'Ottoman Vine', file: 'ottoman-vine.jpg', category: 'celebration', sourceName: 'Turkey, “Fragmentary Loom Width with Wavy-Vine…”, ca. 1565–80 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/451101' },
  { id: 'crimson-velvet', label: 'Crimson Velvet', file: 'crimson-velvet.jpg', category: 'statement', sourceName: '“Panel of velvet”, second half 15th · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/227221' },
  { id: 'palampore', label: 'Palampore', file: 'palampore.jpg', category: 'gathering', sourceName: 'India, “Bed Cover”, 18th century · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/453160' },
  { id: 'hewson-flowers', label: 'Hewson Flowers', file: 'hewson-flowers.jpg', category: 'gathering', sourceName: 'John Hewson, “Quilt center”, ca. 1790 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/19004' },
  { id: 'golden-toile', label: 'Golden Toile', file: 'golden-toile.jpg', category: 'celebration', sourceName: 'Oberkampf Manufactory, “Les Coquecigrues”, ca. 1792 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/222113' },
  { id: 'crewelwork', label: 'Crewelwork', file: 'crewelwork.jpg', category: 'gathering', sourceName: 'Mary Jones, “Sampler”, 1795 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/14100' },
  { id: 'gold-lattice', label: 'Gold Lattice', file: 'gold-lattice.jpg', category: 'celebration', sourceName: 'India, “Pichhwai for the Festival of Cows”, late 18th century · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/65576' },
  { id: 'alsace-clouds', label: 'Alsace Clouds', file: 'alsace-clouds.jpg', category: 'statement', sourceName: '“Textile Design with Cloud-Like Figures…”, 1840 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/709041' },
  { id: 'alsace-branches', label: 'Alsace Branches', file: 'alsace-branches.jpg', category: 'statement', sourceName: '“Textile Design with Scrolling Branches…”, 1840 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/710360' },
  { id: 'alsace-pearls', label: 'Alsace Pearls', file: 'alsace-pearls.jpg', category: 'statement', sourceName: '“Textile Design with Scattered Pearls…”, 1840 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/710698' },
  { id: 'alsace-stripes', label: 'Alsace Stripes', file: 'alsace-stripes.jpg', category: 'statement', sourceName: '“Textile Design with Alternating…”, 1840 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/708875' },
  { id: 'alsace-scrolls', label: 'Alsace Scrolls', file: 'alsace-scrolls.jpg', category: 'statement', sourceName: '“Textile Design of Scattered Pealrs over…”, 1840 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/709353' },
  { id: 'basketweave', label: 'Basketweave', file: 'basketweave.jpg', category: 'statement', sourceName: '“Textile Design with a Basketweave…”, 1840 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/709433' },
  { id: 'alsace-ovals', label: 'Alsace Ovals', file: 'alsace-ovals.jpg', category: 'statement', sourceName: '“Textile Design with Scattered Ovals”, 1840 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/709039' },
  { id: 'star-of-jerusalem', label: 'Star of Jerusalem', file: 'star-of-jerusalem.jpg', category: 'celebration', sourceName: '“Star of Jerusalem Quilt”, ca. 1820 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/854570' },
  { id: 'quilt-rosettes', label: 'Quilt Rosettes', file: 'quilt-rosettes.jpg', category: 'gathering', sourceName: 'American, “Quilt”, ca. 1850 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/854567' },
  { id: 'quilt-triangles', label: 'Quilt Triangles', file: 'quilt-triangles.jpg', category: 'gathering', sourceName: 'American, “Quilt”, ca. 1850 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/855671' },
  { id: 'quilt-mosaic', label: 'Quilt Mosaic', file: 'quilt-mosaic.jpg', category: 'gathering', sourceName: '“Quilt”, 1820–50 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/229936' },
  { id: 'branches-and-vines', label: 'Branches & Vines', file: 'branches-and-vines.jpg', category: 'gathering', sourceName: 'Ernestine Eberhardt Zaumseil, “Branches and Vines Quilt”, ca. 1875 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/625591' },
  { id: 'embroidered-cover', label: 'Embroidered Cover', file: 'embroidered-cover.jpg', category: 'gathering', sourceName: '“Quilt”, central panel and · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/229930' },
  { id: 'crib-quilt', label: 'Crib Quilt', file: 'crib-quilt.jpg', category: 'gathering', sourceName: '“Crib Quilt”, ca. 1860 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/854563' },
  { id: 'hearts-and-chess', label: 'Hearts & Chess', file: 'hearts-and-chess.jpg', category: 'celebration', sourceName: '“Hearts and Chess Pieces Quilt”, ca. 1830 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/854565' },
  { id: 'spiral-stencil', label: 'Spiral Stencil', file: 'spiral-stencil.jpg', category: 'statement', sourceName: 'Japan, “Stencil”, 19th century · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/69941' },
  { id: 'diagonal-stencil', label: 'Diagonal Stencil', file: 'diagonal-stencil.jpg', category: 'statement', sourceName: 'Japan, “Stencil”, 19th century · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/69930' },
  { id: 'lattice-stencil', label: 'Lattice Stencil', file: 'lattice-stencil.jpg', category: 'statement', sourceName: 'Japan, “Stencil”, 19th century · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/69929' },
  { id: 'iznik-cobalt', label: 'Iznik Cobalt', file: 'iznik-cobalt.jpg', category: 'statement', sourceName: 'Turkey, “Tile Panel”, second half 16th · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/447013' },
  { id: 'iznik-turquoise', label: 'Iznik Turquoise', file: 'iznik-turquoise.jpg', category: 'statement', sourceName: 'Turkey, “Tile Panel”, second half 16th · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/447014' },
  { id: 'iznik-carnation', label: 'Iznik Carnation', file: 'iznik-carnation.jpg', category: 'celebration', sourceName: 'Turkey, “Tile Panel”, second half 16th · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/447015' },
  { id: 'damascus-vine', label: 'Damascus Vine', file: 'damascus-vine.jpg', category: 'statement', sourceName: 'Syria, “Tile Panel with Wavy-vine Design”, 16th–17th century · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/447608' },
  { id: 'swallows', label: 'Swallows', file: 'swallows.jpg', category: 'gathering', sourceName: 'Teisai Hokuba, “Spring Rain Collection”, ca. 1820 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/54146' },
  { id: 'marsh-tit', label: 'Marsh Tit', file: 'marsh-tit.jpg', category: 'gathering', sourceName: 'Teisai Hokuba, “Spring Rain Collection”, ca. 1820 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/54147' },
  { id: 'mountain-bird', label: 'Mountain Bird', file: 'mountain-bird.jpg', category: 'gathering', sourceName: 'Teisai Hokuba, “Spring Rain Collection”, ca. 1820 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/54149' },
  { id: 'sparrows', label: 'Sparrows', file: 'sparrows.jpg', category: 'gathering', sourceName: 'Teisai Hokuba, “Spring Rain Collection”, ca. 1820 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/54148' },
  { id: 'cherry-blossom', label: 'Cherry Blossom', file: 'cherry-blossom.jpg', category: 'celebration', sourceName: 'Sakai Hitsu, “Blossoming Cherry Trees”, ca. 1805 · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/53423' },
  { id: 'gilded-pines', label: 'Gilded Pines', file: 'gilded-pines.jpg', category: 'statement', sourceName: 'Tosa Mitsuyoshi, “An Imperial Excursion”, mid-16th–early 17th · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/39665' },
  { id: 'golden-fan', label: 'Golden Fan', file: 'golden-fan.jpg', category: 'gathering', sourceName: 'Kano Motonobu, “Chinese Boys at Play”, first half 16th · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/872017' },
  { id: 'crimson-cord', label: 'Crimson Cord', file: 'crimson-cord.jpg', category: 'statement', sourceName: 'Harukawa Goshichi, “Mirror With the Design of a Nine-Tailed…” · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/55068' },
  { id: 'dresser-arches', label: 'Dresser Arches', file: 'dresser-arches.jpg', category: 'statement', sourceName: 'Christopher Dresser, “Design drawing”, ca. 1883, based on · The Met (CC0)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/363730' },

  // Drawn for RSVPfor rather than sourced: the modern stationery looks a host
  // reaches for first. No licence to honour and nobody to credit.
  { id: 'sage-garland', label: 'Sage Garland', file: 'sage-garland.jpg', category: 'gathering', origin: 'original' },
  { id: 'olive-garland', label: 'Olive Garland', file: 'olive-garland.jpg', category: 'gathering', origin: 'original' },
  { id: 'blush-garland', label: 'Blush Garland', file: 'blush-garland.jpg', category: 'celebration', origin: 'original' },
  { id: 'terracotta-arches', label: 'Terracotta Arches', file: 'terracotta-arches.jpg', category: 'gathering', origin: 'original' },
  { id: 'plum-arches', label: 'Plum Arches', file: 'plum-arches.jpg', category: 'celebration', origin: 'original' },
  { id: 'teal-arches', label: 'Teal Arches', file: 'teal-arches.jpg', category: 'statement', origin: 'original' },
  { id: 'carnival-stripes', label: 'Carnival Stripes', file: 'carnival-stripes.jpg', category: 'celebration', origin: 'original' },
  { id: 'berry-stripes', label: 'Berry Stripes', file: 'berry-stripes.jpg', category: 'celebration', origin: 'original' },
  { id: 'harbour-stripes', label: 'Harbour Stripes', file: 'harbour-stripes.jpg', category: 'statement', origin: 'original' },
  { id: 'sunset-waves', label: 'Sunset Waves', file: 'sunset-waves.jpg', category: 'gathering', origin: 'original' },
  { id: 'ocean-waves', label: 'Ocean Waves', file: 'ocean-waves.jpg', category: 'gathering', origin: 'original' },
  { id: 'dusk-waves', label: 'Dusk Waves', file: 'dusk-waves.jpg', category: 'statement', origin: 'original' },
  { id: 'terrazzo', label: 'Terrazzo', file: 'terrazzo.jpg', category: 'gathering', origin: 'original' },
  { id: 'pastel-terrazzo', label: 'Pastel Terrazzo', file: 'pastel-terrazzo.jpg', category: 'gathering', origin: 'original' },
  { id: 'ink-terrazzo', label: 'Ink Terrazzo', file: 'ink-terrazzo.jpg', category: 'statement', origin: 'original' },
  { id: 'midnight-confetti', label: 'Midnight Confetti', file: 'midnight-confetti.jpg', category: 'celebration', origin: 'original' },
  { id: 'blush-confetti', label: 'Blush Confetti', file: 'blush-confetti.jpg', category: 'celebration', origin: 'original' },
  { id: 'emerald-confetti', label: 'Emerald Confetti', file: 'emerald-confetti.jpg', category: 'celebration', origin: 'original' },
  { id: 'neon-dusk', label: 'Neon Dusk', file: 'neon-dusk.jpg', category: 'statement', origin: 'original' },
  { id: 'cool-mesh', label: 'Cool Mesh', file: 'cool-mesh.jpg', category: 'statement', origin: 'original' },
  { id: 'paper-cutouts', label: 'Paper Cutouts', file: 'paper-cutouts.jpg', category: 'gathering', origin: 'original' },
  { id: 'jewel-cutouts', label: 'Jewel Cutouts', file: 'jewel-cutouts.jpg', category: 'gathering', origin: 'original' },
  { id: 'pastel-cutouts', label: 'Pastel Cutouts', file: 'pastel-cutouts.jpg', category: 'gathering', origin: 'original' },
  { id: 'deco-gold', label: 'Deco Gold', file: 'deco-gold.jpg', category: 'statement', origin: 'original' },
  { id: 'deco-emerald', label: 'Deco Emerald', file: 'deco-emerald.jpg', category: 'statement', origin: 'original' },
  { id: 'deco-rose', label: 'Deco Rose', file: 'deco-rose.jpg', category: 'celebration', origin: 'original' },
  { id: 'liquid-sunset', label: 'Liquid Sunset', file: 'liquid-sunset.jpg', category: 'statement', origin: 'original' },
  { id: 'liquid-ocean', label: 'Liquid Ocean', file: 'liquid-ocean.jpg', category: 'statement', origin: 'original' },
  { id: 'liquid-sand', label: 'Liquid Sand', file: 'liquid-sand.jpg', category: 'statement', origin: 'original' },

  { id: 'cocktail-party', label: 'Cocktail Party', file: 'cocktail-party.png', category: 'statement', sourceName: 'Photo by Matt Bango · StockSnap.io (CC0)', sourceUrl: 'https://stocksnap.io/photo/alcohol-cocktail-NEKGIFYCL4' },
  { id: 'garden-party', label: 'Garden Party', file: 'garden-party.png', category: 'gathering', sourceName: 'Photo by Vikram Mudaliar · StockSnap.io (CC0)', sourceUrl: 'https://stocksnap.io/photo/bougainvillea-flowers-VZWH4VMI19' },
  { id: 'pool-party', label: 'Pool Party', file: 'pool-party.png', category: 'gathering', sourceName: 'Rawpixel (Public Domain)', sourceUrl: 'https://www.rawpixel.com/image/5917171/image-public-domain-summer-water' },
  { id: 'game-night', label: 'Game Night', file: 'game-night.png', category: 'gathering', sourceName: 'Photo by Candace McDaniel · StockSnap.io (CC0)', sourceUrl: 'https://stocksnap.io/photo/lucky-dice-X8CPTKKQEX' },
  { id: 'brunch', label: 'Brunch', file: 'brunch.png', category: 'gathering', sourceName: 'Photo by Tilak Bahadur Karki · WordPress Photos (CC0)', sourceUrl: 'https://wordpress.org/photos/photo/7176a2a49a/' },
  { id: 'dinner-party', label: 'Dinner Party', file: 'dinner-party.png', category: 'statement', sourceName: 'Photo by WDnet Studio · StockSnap.io (CC0)', sourceUrl: 'https://stocksnap.io/photo/finedining-dinner-UAOW7BNH2M' },
  { id: 'halloween', label: 'Halloween', file: 'halloween.png', category: 'celebration', sourceName: 'Photo by Toyah Anette B · Wikimedia Commons (CC0)', sourceUrl: 'https://commons.wikimedia.org/w/index.php?curid=153193086' },
  { id: 'thanksgiving', label: 'Thanksgiving', file: 'thanksgiving.png', category: 'gathering', sourceName: 'Photo by Element5 Digital · StockSnap.io (CC0)', sourceUrl: 'https://stocksnap.io/photo/thanksgiving-autumn-Q1D4QEQM3Z' },
  { id: 'fourth-of-july', label: 'Fourth of July', file: 'fourth-of-july.png', category: 'celebration', sourceName: 'Rawpixel (Public Domain)', sourceUrl: 'https://www.rawpixel.com/image/6038039/photo-image-lights-public-domain-celebration' },
  { id: 'gender-reveal', label: 'Gender Reveal', file: 'gender-reveal.png', category: 'celebration', sourceName: 'Photo by Burak Kebapci · StockSnap.io (CC0)', sourceUrl: 'https://stocksnap.io/photo/balloon-colorful-ZZI582DSTA' },
  { id: 'bridal-shower', label: 'Bridal Shower', file: 'bridal-shower.png', category: 'celebration', sourceName: 'Rawpixel (Public Domain)', sourceUrl: 'https://www.rawpixel.com/image/6040025/photo-image-flower-public-domain-hand' },
  { id: 'bachelorette-party', label: 'Bachelorette Party', file: 'bachelorette-party.png', category: 'celebration', sourceName: 'Photo by Kristin Hardwick · StockSnap.io (CC0)', sourceUrl: 'https://stocksnap.io/photo/champagne-bottle-ZLASC4UKIX' },
  { id: 'reunion', label: 'Reunion', file: 'reunion.png', category: 'gathering', sourceName: 'Photo by Tohm Brigitte · StockSnap.io (CC0)', sourceUrl: 'https://stocksnap.io/photo/picnic-food-ZMJIH1NTZ1' },
  { id: 'welcome-party', label: 'Welcome Party', file: 'welcome-party.png', category: 'gathering', sourceName: 'Rawpixel (Public Domain)', sourceUrl: 'https://www.rawpixel.com/image/5919428/image-light-public-domain-free' },
];

function findTemplate(id) {
  return TEMPLATES.find((t) => t.id === id);
}

module.exports = { TEMPLATES, findTemplate };
